# =============================================================================
# app.py — Ghost Worker / Fraud Detection API
# Deployed on Hugging Face Spaces
#
# Endpoints:
#   GET  /health  — liveness check
#   POST /score   — upload a payroll CSV/Excel and receive a fraud analysis
#   GET  /docs    — Swagger UI (auto-generated by FastAPI)
#
# Detection pipeline:
#   1.  Parse uploaded CSV/Excel payroll file
#   2.  ★ Resolve column names to the canonical schema via a two-tier mapper:
#         Tier 1 — rapidfuzz (local, zero-latency, zero-cost fuzzy matching)
#         Tier 2 — Gemini Flash (API fallback, only for columns Tier 1 can't
#                  resolve above the confidence threshold)
#   3.  Detect scan type (PAYROLL_SCAN vs RINSE_SCAN) from mapped columns
#   4.  Normalise salary values (handle frequency variants and string formats)
#   5.  Engineer Rinse-only features (same_day_joiners, salary_roundness, etc.)
#   6.  Score each employee via an ensemble:
#         PAYROLL_SCAN → 70% XGBoost (full) + 30% Isolation Forest
#         RINSE_SCAN   → 100% XGBoost (rinse, lightweight)
#   7.  Convert raw ensemble probability to a 0–100 trust score
#   8.  Assign payment tier, risk level, and recommended action
#   9.  Build rule-based anomaly list and binary signal flags
#   10. Concurrently generate Gemini AI audit explanations for flagged employees
#   11. Return structured JSON conforming to the canonical response schema v2
#
# ── Column mapping strategy (Step 2) ─────────────────────────────────────────
#
#   The two-tier resolver runs ONCE per uploaded file on column headers only
#   (not on data rows), so it is fast and cheap regardless of file size.
#
#   Tier 1 — rapidfuzz token_sort_ratio  (LOCAL, zero API calls)
#     Handles: case differences, whitespace, underscores vs spaces, common
#     abbreviations, and minor typos (≤2–3 character edits).
#
#     Examples resolved automatically:
#       "Monthly Salary"  → monthly_salary    (case + space)
#       "montly_salary"   → monthly_salary    (typo)
#       "salaries"        → monthly_salary    (synonym in alias table)
#       "Dept"            → Department        (abbreviation in alias table)
#       "Acct Age Mths"   → Acct Age (Mths)   (punctuation dropped)
#       "days absent"     → Total Days Absent (alias table)
#
#     A match is accepted when similarity ≥ FUZZY_THRESHOLD (default 72).
#     Columns below the threshold are forwarded to Tier 2.
#
#   Tier 2 — Gemini 2.5 Flash  (API fallback, ONE call per file max)
#     Called only when Tier 1 leaves ≥1 unresolved canonical column AND
#     there are unmapped client columns that might carry that data.
#     Sends only the header strings (not data rows) — token cost is
#     negligible (~200–400 input tokens per file).
#     Fails gracefully: unresolved columns are imputed with 0.
#
#   Why not Gemini for everything?
#     • Gemini has a free-tier RPM/RPD limit; calling it per employee or per
#       file for a large batch would exhaust quota quickly.
#     • Tier 1 resolves the vast majority of real-world cases with zero latency
#       and zero cost.  Tier 2 is a safety net, not the primary path.
#
# Response schema version: 2.0
# =============================================================================

import asyncio
import io
import json
import os
import pickle
import re
import time
import uuid
from datetime import datetime, timezone

import httpx
import numpy as np
import pandas as pd
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from rapidfuzz import fuzz
from rapidfuzz import process as fuzz_process

# =============================================================================
# ENVIRONMENT / SECRETS
# Set these as HF Space Secrets — never hard-code values here.
# =============================================================================

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
DIVINE_WEBHOOK = os.environ.get("WEBHOOK", "")  # Reserved for future webhook use

# Embedded in every response for auditability and rollback tracking.
MODEL_VERSION = "1.1.0"
RULESET_VERSION = "1.1.0"

# Minimum rapidfuzz similarity (0–100) to accept a column match in Tier 1.
# 72 accepts "montly_salary" (typo) and "Monthly Salary" (case+space) while
# rejecting genuinely unrelated column names.  Lower → more recall, more risk
# of wrong mappings.  Raise to 80+ for stricter matching.
FUZZY_THRESHOLD = 72

# =============================================================================
# MODEL LOADING
# All artefacts must be present in the HF Space repo root.
# The app crashes at startup if any are missing — intentional fail-fast.
# =============================================================================

with open("iso_forest_model.pkl", "rb") as f:
    iso_model = pickle.load(f)  # Isolation Forest — unsupervised anomaly detector

with open("xgb_model.pkl", "rb") as f:
    xgb_full = pickle.load(f)  # XGBoost — full feature set (attendance + payroll)

_rinse_file = (
    "xgb_rinse_model_new.pkl" if MODEL_VERSION != "1.0.0" else "xgb_rinse_model.pkl"
)
with open(_rinse_file, "rb") as f:
    xgb_rinse = pickle.load(f)  # XGBoost — payroll-only features (no attendance)

with open("label_encoder.pkl", "rb") as f:
    le = pickle.load(f)  # LabelEncoder for categorical columns

print("All models loaded successfully.")

# =============================================================================
# FEATURE COLUMN DEFINITIONS
# Order matters — XGBoost is sensitive to column order at inference time.
# =============================================================================

FULL_FEATURE_COLUMNS = [
    "Gender",
    "State",
    "Department",
    "Job Title",
    "Grade",
    "monthly_salary",
    "band_min",
    "band_max",
    "Bank Name",
    "Acct Age (Mths)",
    "attendance_pct",
    "Monthly Txns",
    "BVN Acct Count",
    "days_tenure",
    "days_since_active",
    "Months on Record",
    "Total Working Days",
    "Total Days Present",
    "Total Days Absent",
    "Total Days Leave",
    "Avg Presence %",
    "Months w/ Zero Attend.",
    "Max Consec. Zero Mths",
    "Avg CI Variance (mins)",
    "Avg Unique Locations",
]

RINSE_BASE_FEATURES = [
    "Gender",
    "State",
    "Department",
    "Job Title",
    "Grade",
    "monthly_salary",
    "band_min",
    "band_max",
    "Bank Name",
    "Acct Age (Mths)",
    "attendance_pct",
    "Monthly Txns",
    "BVN Acct Count",
    "days_tenure",
    "days_since_active",
]

RINSE_FEATURE_COLUMNS = RINSE_BASE_FEATURES + [
    "same_day_joiners",  # Count of employees sharing the same join date
    "salary_roundness",  # 1 if salary is a round multiple of 10,000
    "salary_band_violation",  # 1 if salary >130% band_max or <70% band_min
    "salary_deviation",  # Normalised salary position within the grade band
]

CATEGORICAL_COLS = ["Gender", "State", "Department", "Job Title", "Bank Name"]

ATTENDANCE_COLS = [
    "Months on Record",
    "Total Working Days",
    "Total Days Present",
    "Total Days Absent",
    "Total Days Leave",
    "Avg Presence %",
    "Months w/ Zero Attend.",
    "Max Consec. Zero Mths",
    "Avg CI Variance (mins)",
    "Avg Unique Locations",
]

# Union of all canonical columns across both scan types.
ALL_CANONICAL_COLS = list(dict.fromkeys(FULL_FEATURE_COLUMNS + RINSE_FEATURE_COLUMNS))

# =============================================================================
# COLUMN ALIAS TABLE
# Maps common alternative names, abbreviations, and semantic synonyms to the
# exact canonical column name expected by the models.
#
# rapidfuzz handles minor typos automatically (e.g. "montly_salary").
# Aliases are needed for semantic differences that edit-distance can't resolve
# (e.g. "salaries" → "monthly_salary", "dept" → "Department").
#
# HOW TO EXTEND:
#   Add a row:  "new client variant": "Canonical Column Name"
#   Key:   any case; spaces, underscores, or hyphens all work.
#   Value: must exactly match one of the strings in ALL_CANONICAL_COLS.
# =============================================================================

COLUMN_ALIASES: dict[str, str] = {
    # ── Salary ────────────────────────────────────────────────────────────────
    "salary": "monthly_salary",
    "salaries": "monthly_salary",
    "gross salary": "monthly_salary",
    "gross_salary": "monthly_salary",
    "basic salary": "monthly_salary",
    "basic_salary": "monthly_salary",
    "base salary": "monthly_salary",
    "base_salary": "monthly_salary",
    "monthly pay": "monthly_salary",
    "monthly_pay": "monthly_salary",
    "pay": "monthly_salary",
    "remuneration": "monthly_salary",
    "compensation": "monthly_salary",
    "monthly gross": "monthly_salary",
    "emolument": "monthly_salary",
    "ctc": "monthly_salary",  # Cost-to-company
    # ── Grade band ────────────────────────────────────────────────────────────
    "min salary": "band_min",
    "min_salary": "band_min",
    "salary min": "band_min",
    "band minimum": "band_min",
    "grade min": "band_min",
    "scale min": "band_min",
    "max salary": "band_max",
    "max_salary": "band_max",
    "salary max": "band_max",
    "band maximum": "band_max",
    "grade max": "band_max",
    "scale max": "band_max",
    # ── Attendance ────────────────────────────────────────────────────────────
    "days absent": "Total Days Absent",
    "absent days": "Total Days Absent",
    "total absent": "Total Days Absent",
    "no of absent days": "Total Days Absent",
    "days present": "Total Days Present",
    "present days": "Total Days Present",
    "total present": "Total Days Present",
    "no of present days": "Total Days Present",
    "working days": "Total Working Days",
    "work days": "Total Working Days",
    "days worked": "Total Working Days",
    "total work days": "Total Working Days",
    "leave days": "Total Days Leave",
    "days on leave": "Total Days Leave",
    "total leave": "Total Days Leave",
    "attendance %": "Avg Presence %",
    "attendance rate": "Avg Presence %",
    "presence": "Avg Presence %",
    "avg attendance": "Avg Presence %",
    "attendance score": "Avg Presence %",
    "zero attendance months": "Months w/ Zero Attend.",
    "zero attend months": "Months w/ Zero Attend.",
    "months zero attendance": "Months w/ Zero Attend.",
    "months with no attendance": "Months w/ Zero Attend.",
    "consecutive zero months": "Max Consec. Zero Mths",
    "max zero months": "Max Consec. Zero Mths",
    "max consecutive absent": "Max Consec. Zero Mths",
    "ci variance": "Avg CI Variance (mins)",
    "clock variance": "Avg CI Variance (mins)",
    "checkin variance": "Avg CI Variance (mins)",
    "check in variance": "Avg CI Variance (mins)",
    "unique locations": "Avg Unique Locations",
    "location count": "Avg Unique Locations",
    "num locations": "Avg Unique Locations",
    "months recorded": "Months on Record",
    "months on payroll": "Months on Record",
    # ── Department ────────────────────────────────────────────────────────────
    "dept": "Department",
    "division": "Department",
    "unit": "Department",
    "directorate": "Department",
    "cost centre": "Department",
    "cost_centre": "Department",
    "ministry": "Department",
    # ── Job title ─────────────────────────────────────────────────────────────
    "position": "Job Title",
    "role": "Job Title",
    "designation": "Job Title",
    "title": "Job Title",
    "job_title": "Job Title",
    "job role": "Job Title",
    "cadre": "Job Title",
    # ── Grade ─────────────────────────────────────────────────────────────────
    "level": "Grade",
    "pay grade": "Grade",
    "pay_grade": "Grade",
    "salary grade": "Grade",
    "step": "Grade",
    "grade level": "Grade",
    "rank": "Grade",
    # ── Bank ──────────────────────────────────────────────────────────────────
    "bank": "Bank Name",
    "bank_name": "Bank Name",
    "financial institution": "Bank Name",
    "payment bank": "Bank Name",
    # ── Account age ───────────────────────────────────────────────────────────
    "account age": "Acct Age (Mths)",
    "acct age": "Acct Age (Mths)",
    "account age months": "Acct Age (Mths)",
    "acct age months": "Acct Age (Mths)",
    "bank account age": "Acct Age (Mths)",
    "account age mths": "Acct Age (Mths)",
    # ── Transactions ──────────────────────────────────────────────────────────
    "transactions": "Monthly Txns",
    "monthly transactions": "Monthly Txns",
    "txns": "Monthly Txns",
    "monthly txn": "Monthly Txns",
    "num transactions": "Monthly Txns",
    "transaction count": "Monthly Txns",
    # ── BVN ───────────────────────────────────────────────────────────────────
    "bvn count": "BVN Acct Count",
    "bvn accounts": "BVN Acct Count",
    "bvn linked accounts": "BVN Acct Count",
    "number of bvn accounts": "BVN Acct Count",
    # ── Tenure ────────────────────────────────────────────────────────────────
    "tenure": "days_tenure",
    "days employed": "days_tenure",
    "employment days": "days_tenure",
    "length of service days": "days_tenure",
    "days since joined": "days_tenure",
    "service days": "days_tenure",
    "days since active": "days_since_active",
    "last active days": "days_since_active",
    "inactive days": "days_since_active",
    "days since last active": "days_since_active",
    # ── Attendance pct ────────────────────────────────────────────────────────
    "attendance pct": "attendance_pct",
    "attend pct": "attendance_pct",
    "attendance percentage": "attendance_pct",
    "pct present": "attendance_pct",
    # ── Gender / State ────────────────────────────────────────────────────────
    "sex": "Gender",
    "province": "State",
    "region": "State",
    "lga": "State",
    "state of origin": "State",
}

# =============================================================================
# SCHEMA / ENUM CONSTANTS
# Centralised so extending the schema never requires hunting through
# business-logic functions.
# =============================================================================


class ScanType:
    RINSE = "RINSE_SCAN"
    PAYROLL = "PAYROLL_SCAN"


class ScanStatus:
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class PaymentTier:
    VERIFIED = "VERIFIED"
    REVIEW = "REVIEW"
    BLOCKED = "BLOCKED"


class RiskLevel:
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AnalysisStatus:
    CLEAR = "CLEAR"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    GHOST_FLAGGED = "GHOST_FLAGGED"
    BLOCKED = "BLOCKED"
    UNDER_INVESTIGATION = "UNDER_INVESTIGATION"


class RecommendedAction:
    APPROVE = "APPROVE"
    REVIEW = "REVIEW"
    BLOCK = "BLOCK"
    ESCALATE = "ESCALATE"
    MANUAL_VERIFICATION = "MANUAL_VERIFICATION"
    AUDITOR_REVIEW = "AUDITOR_REVIEW"


class AnomalyType:
    DUPLICATE_BVN = "DUPLICATE_BVN"
    DUPLICATE_NIN = "DUPLICATE_NIN"
    SALARY_ANOMALY = "SALARY_ANOMALY"
    GHOST_PATTERN = "GHOST_PATTERN"
    SYNTHETIC_IDENTITY = "SYNTHETIC_IDENTITY"
    ATTENDANCE_ANOMALY = "ATTENDANCE_ANOMALY"
    DEVICE_ANOMALY = "DEVICE_ANOMALY"
    LOCATION_ANOMALY = "LOCATION_ANOMALY"
    LIVENESS_FAILURE = "LIVENESS_FAILURE"
    MULTIPLE_BANK_USAGE = "MULTIPLE_BANK_USAGE"
    ROUND_SALARY_PATTERN = "ROUND_SALARY_PATTERN"
    BULK_JOIN_PATTERN = "BULK_JOIN_PATTERN"


class AnomalySeverity:
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class EmploymentType:
    FULL_TIME = "FULL_TIME"
    PART_TIME = "PART_TIME"
    CONTRACT = "CONTRACT"
    INTERN = "INTERN"
    TEMPORARY = "TEMPORARY"


class EmploymentStatus:
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"
    TERMINATED = "TERMINATED"
    ON_LEAVE = "ON_LEAVE"


class Gender:
    MALE = "MALE"
    FEMALE = "FEMALE"
    OTHER = "OTHER"


# =============================================================================
# COLUMN MAPPING — TIER 1: RAPIDFUZZ  (LOCAL, ZERO COST)
# =============================================================================


def _normalise_key(s: str) -> str:
    """Prepare a column name for fuzzy comparison.

    Lowercases, replaces structural separators with spaces, removes
    punctuation that carries no semantic meaning, and collapses whitespace.

    This makes "Acct Age (Mths)" and "acct age mths" compare as near-identical,
    and lets token_sort_ratio handle word-order differences like
    "salary monthly" vs "monthly salary".

    Args:
        s: Raw column name string.

    Returns:
        Normalised comparison key.
    """
    s = s.lower().strip()
    s = re.sub(r"[_\-/\\]", " ", s)  # underscores / hyphens → space
    s = re.sub(r"[()%.,#@!?]", "", s)  # drop punctuation with no meaning
    s = re.sub(r"\s+", " ", s).strip()
    return s


# Pre-build lookup tables once at import time (not per request).
_NORM_CANONICAL: dict[str, str] = {_normalise_key(c): c for c in ALL_CANONICAL_COLS}
_NORM_ALIASES: dict[str, str] = {
    _normalise_key(k): v for k, v in COLUMN_ALIASES.items()
}

_CANONICAL_NORM_LIST = list(_NORM_CANONICAL.keys())
_ALIAS_NORM_LIST = list(_NORM_ALIASES.keys())


def resolve_columns_fuzzy(
    client_cols: list[str],
) -> tuple[dict[str, str], list[str]]:
    """Map client column names to canonical names via aliases and fuzzy matching.

    Resolution order for each client column:
        1. Exact match against normalised canonical names.
        2. Exact match against normalised alias table.
        3. Best fuzzy match against canonical names (score ≥ FUZZY_THRESHOLD).
        4. Best fuzzy match against alias keys  (score ≥ FUZZY_THRESHOLD).

    token_sort_ratio is used rather than plain ratio because it is
    insensitive to word order ("salary monthly" == "monthly salary").

    Args:
        client_cols: Column names as read from the uploaded file (stripped).

    Returns:
        mapping:    {client_col → canonical_col} for all resolved columns.
        unresolved: canonical columns still not found after Tier 1.
    """
    mapping: dict[str, str] = {}
    already_mapped: set[str] = set()  # prevent two client cols claiming one canonical

    for col in client_cols:
        norm = _normalise_key(col)

        # 1. Exact canonical match
        if norm in _NORM_CANONICAL:
            canon = _NORM_CANONICAL[norm]
            if canon not in already_mapped:
                mapping[col] = canon
                already_mapped.add(canon)
                continue

        # 2. Exact alias match
        if norm in _NORM_ALIASES:
            canon = _NORM_ALIASES[norm]
            if canon not in already_mapped:
                mapping[col] = canon
                already_mapped.add(canon)
                continue

        # 3. Fuzzy match against canonical names
        best_canon = fuzz_process.extractOne(
            norm,
            _CANONICAL_NORM_LIST,
            scorer=fuzz.token_sort_ratio,
            score_cutoff=FUZZY_THRESHOLD,
        )
        if best_canon:
            canon = _NORM_CANONICAL[best_canon[0]]
            if canon not in already_mapped:
                mapping[col] = canon
                already_mapped.add(canon)
                continue

        # 4. Fuzzy match against alias keys
        best_alias = fuzz_process.extractOne(
            norm,
            _ALIAS_NORM_LIST,
            scorer=fuzz.token_sort_ratio,
            score_cutoff=FUZZY_THRESHOLD,
        )
        if best_alias:
            canon = _NORM_ALIASES[best_alias[0]]
            if canon not in already_mapped:
                mapping[col] = canon
                already_mapped.add(canon)
                continue

    # Identify which canonical columns are still unmapped after Tier 1.
    unresolved = [c for c in ALL_CANONICAL_COLS if c not in already_mapped]
    return mapping, unresolved


# =============================================================================
# COLUMN MAPPING — TIER 2: GEMINI FLASH  (API FALLBACK, ONE CALL PER FILE)
# Only invoked when Tier 1 leaves unresolved canonical columns AND there are
# still unclaimed client columns that might carry that data.
# =============================================================================


async def resolve_columns_gemini(
    unmapped_client_cols: list[str],
    already_mapped_canon: set[str],
    unresolved_canonical: list[str],
) -> dict[str, str]:
    """Ask Gemini 2.5 Flash to map remaining client columns to canonical targets.

    The prompt contains only column header strings (not data rows), keeping
    token usage negligible regardless of file size.

    The model is instructed to:
        • Return ONLY a JSON object {client_col: canonical_col}
        • Include only confident mappings
        • Never invent new canonical column names
        • Skip columns it cannot resolve

    The response is validated — only mappings whose value is a known canonical
    column and whose target hasn't already been claimed are accepted.

    Args:
        unmapped_client_cols:  Client columns not yet claimed by Tier 1.
        already_mapped_canon:  Canonical columns already resolved (do not remap).
        unresolved_canonical:  Canonical columns still needed.

    Returns:
        {client_col → canonical_col} for additionally resolved columns.
        Empty dict on any failure (graceful degradation).
    """
    prompt = f"""You are a data-schema mapping assistant for a payroll fraud detection system.

Map column names from a client's uploaded CSV to the canonical column names our models need.

CLIENT COLUMNS TO MAP (not yet resolved):
{json.dumps(unmapped_client_cols, indent=2)}

CANONICAL COLUMNS STILL NEEDED:
{json.dumps(unresolved_canonical, indent=2)}

ALREADY RESOLVED (do NOT remap these canonical columns):
{json.dumps(sorted(already_mapped_canon), indent=2)}

Rules:
- Return ONLY a valid JSON object: {{"client_col": "canonical_col", ...}}
- Values must be exact strings from CANONICAL COLUMNS STILL NEEDED.
- Only include mappings you are confident about.
- Do not invent new canonical column names.
- Do not remap any column in ALREADY RESOLVED.
- If a client column cannot be mapped confidently, omit it entirely.
- No markdown, no backticks, no explanations. Pure JSON only."""

    try:
        async with httpx.AsyncClient(timeout=25) as client:
            resp = await client.post(
                "https://generativelanguage.googleapis.com/v1beta/models/"
                f"gemini-2.5-flash:generateContent?key={GEMINI_API_KEY}",
                headers={"Content-Type": "application/json"},
                json={
                    "contents": [{"parts": [{"text": prompt}]}],
                    "generationConfig": {
                        "maxOutputTokens": 512,
                        "temperature": 0.0,  # Deterministic — this is a lookup task
                    },
                },
            )
        raw_text = resp.json()["candidates"][0]["content"]["parts"][0]["text"].strip()

        # Strip accidental markdown fences before parsing.
        raw_text = re.sub(r"^```[a-z]*\n?", "", raw_text)
        raw_text = re.sub(r"\n?```$", "", raw_text).strip()

        gemini_map: dict = json.loads(raw_text)

        # Validate: only accept mappings to known canonical targets not yet claimed.
        canonical_set = set(ALL_CANONICAL_COLS)
        claimed = set(already_mapped_canon)
        validated: dict[str, str] = {}

        for client_col, canon_col in gemini_map.items():
            if (
                isinstance(client_col, str)
                and isinstance(canon_col, str)
                and canon_col in canonical_set
                and canon_col not in claimed
            ):
                validated[client_col] = canon_col
                claimed.add(canon_col)

        print(
            f"[ColumnMapper] Gemini Tier 2 resolved {len(validated)} column(s): "
            f"{list(validated.values())}"
        )
        return validated

    except Exception as exc:
        print(
            f"[ColumnMapper] Gemini Tier 2 failed ({exc}) — unresolved columns imputed with 0."
        )
        return {}


# =============================================================================
# COLUMN MAPPING — ORCHESTRATOR
# Runs Tier 1, then conditionally Tier 2, then renames the DataFrame.
# =============================================================================


async def map_columns(df: pd.DataFrame) -> tuple[pd.DataFrame, dict]:
    """Resolve client column names to canonical names and rename the DataFrame.

    Orchestration:
        1. Strip whitespace from all headers.
        2. Run Tier 1 (fuzzy) resolver.
        3. If there are still unresolved canonical columns AND unclaimed client
           columns (potential hidden matches), call Tier 2 (Gemini).
        4. Merge mappings (Tier 1 takes precedence on conflicts).
        5. Rename DataFrame columns.
        6. Return renamed DataFrame + final mapping (stored in scan_metadata
           as an audit trail so callers can see exactly what was resolved).

    Args:
        df: Raw DataFrame as parsed from the uploaded file.

    Returns:
        df:      DataFrame with columns renamed to canonical names where resolved.
        mapping: Final {original_col → canonical_col} dict for audit/logging.
    """
    # Step 1: strip whitespace
    df.columns = df.columns.str.strip()
    client_cols = list(df.columns)

    # Step 2: Tier 1 fuzzy resolution
    tier1_map, unresolved = resolve_columns_fuzzy(client_cols)
    already_mapped = set(tier1_map.values())

    # Step 3: Tier 2 Gemini fallback (only when useful and API key is set)
    unclaimed_clients = [c for c in client_cols if c not in tier1_map]
    tier2_map: dict[str, str] = {}

    if unresolved and unclaimed_clients and GEMINI_API_KEY:
        tier2_map = await resolve_columns_gemini(
            unclaimed_clients, already_mapped, unresolved
        )

    # Step 4: Merge — Tier 1 takes precedence
    final_map = {**tier2_map, **tier1_map}

    # Step 5: Rename
    df = df.rename(columns=final_map)

    # Step 6: Log summary
    still_missing = [c for c in ALL_CANONICAL_COLS if c not in df.columns]
    print(
        f"[ColumnMapper] Resolved {len(final_map)} column(s) "
        f"(Tier1={len(tier1_map)}, Tier2={len(tier2_map)}). "
        f"Still missing (→imputed 0): {still_missing or 'none'}"
    )

    return df, final_map


# =============================================================================
# SALARY NORMALISATION
# =============================================================================


def normalise_salary(df: pd.DataFrame) -> pd.DataFrame:
    """Convert salary values to a consistent monthly figure.

    Some payroll exports record bi-weekly, weekly, or hourly figures.
    Detects an optional pay-frequency column and converts accordingly.

    Supported pay_frequency strings (case-insensitive):
        monthly  (default / no conversion)
        bi-weekly | twice monthly | bi-monthly | fortnightly  → ×2
        weekly                                                 → ×4.33
        hourly | per hour | hour                               → ×hours_per_week×4.33

    Also handles string salaries with currency symbols and comma separators
    (e.g. "₦85,000", "$12,500").

    Args:
        df: DataFrame; must contain "monthly_salary" to have any effect.

    Returns:
        DataFrame with monthly_salary normalised to a true monthly amount.
    """
    if "monthly_salary" not in df.columns:
        return df

    freq_col = None
    for col in df.columns:
        if col.lower().strip() in (
            "pay frequency",
            "frequency",
            "payment type",
            "pay type",
            "pay cycle",
            "salary type",
        ):
            freq_col = col
            break

    if freq_col:

        def convert(row):
            freq = str(row[freq_col]).lower().strip()
            sal = row["monthly_salary"]
            if freq in ("bi-weekly", "twice monthly", "bi-monthly", "fortnightly"):
                return sal * 2
            elif freq in ("hourly", "per hour", "hour"):
                hours = row.get("hours_per_week", 40)
                return sal * hours * 4.33
            elif freq in ("weekly",):
                return sal * 4.33
            return sal

        df["monthly_salary"] = df.apply(convert, axis=1)

    if df["monthly_salary"].dtype == object:
        df["monthly_salary"] = (
            df["monthly_salary"].astype(str).str.replace(r"[₦$£€,\s]", "", regex=True)
        )
        df["monthly_salary"] = pd.to_numeric(
            df["monthly_salary"], errors="coerce"
        ).fillna(0)

    return df


# =============================================================================
# RINSE FEATURE ENGINEERING
# =============================================================================


def engineer_rinse_features(df: pd.DataFrame) -> pd.DataFrame:
    """Derive the four engineered features required by the RINSE_SCAN model.

    Features:
        same_day_joiners      — employees sharing this join date (spike = bulk fraud).
        salary_roundness      — 1 if salary is a round ×10,000 (fabricated record signal).
        salary_band_violation — 1 if salary >130% band_max or <70% band_min.
        salary_deviation      — normalised salary position in band [0=min, 1=max].

    If required base columns are missing from the DataFrame, the derived feature
    is set to 0 (no anomaly signal).

    Args:
        df: DataFrame with days_tenure, monthly_salary, band_min, band_max.

    Returns:
        DataFrame with four new feature columns appended.
    """
    if "days_tenure" in df.columns:
        join_counts = df["days_tenure"].value_counts()
        df["same_day_joiners"] = df["days_tenure"].map(join_counts)
    else:
        df["same_day_joiners"] = 0

    if "monthly_salary" in df.columns:
        df["salary_roundness"] = (df["monthly_salary"] % 10000 == 0).astype(int)
    else:
        df["salary_roundness"] = 0

    has_band = (
        "monthly_salary" in df.columns
        and "band_min" in df.columns
        and "band_max" in df.columns
    )
    if has_band:
        df["salary_above_band"] = (df["monthly_salary"] > df["band_max"] * 1.3).astype(int)
        df["salary_below_band"] = (df["monthly_salary"] < df["band_min"] * 0.7).astype(int)
        df["salary_band_violation"] = (
            df["salary_above_band"] | df["salary_below_band"]
        ).astype(int)
        df["salary_deviation"] = (df["monthly_salary"] - df["band_min"]) / (
            df["band_max"] - df["band_min"] + 1
        )
    else:
        df["salary_band_violation"] = 0
        df["salary_deviation"] = 0.0
    return df


# =============================================================================
# TIER / RISK / ACTION ASSIGNMENT HELPERS
# =============================================================================


def assign_tier(score: float) -> str:
    """Map a 0–100 trust score to a payment tier.
    ≥75 → VERIFIED  (low risk)
    ≥50 → REVIEW    (medium risk)
     <50 → BLOCKED   (high/critical risk)
    """
    if score >= 75:
        return PaymentTier.VERIFIED
    elif score >= 50:
        return PaymentTier.REVIEW
    return PaymentTier.BLOCKED


def assign_risk_level(score: float) -> str:
    """Map a 0–100 trust score to a qualitative risk level (inverse of trust).
    ≥75 → LOW | ≥50 → MEDIUM | ≥25 → HIGH | <25 → CRITICAL
    """
    if score >= 75:
        return RiskLevel.LOW
    elif score >= 50:
        return RiskLevel.MEDIUM
    elif score >= 25:
        return RiskLevel.HIGH
    return RiskLevel.CRITICAL


def assign_analysis_status(tier: str) -> str:
    return {
        PaymentTier.VERIFIED: AnalysisStatus.CLEAR,
        PaymentTier.REVIEW: AnalysisStatus.REVIEW_REQUIRED,
        PaymentTier.BLOCKED: AnalysisStatus.GHOST_FLAGGED,
    }.get(tier, AnalysisStatus.UNDER_INVESTIGATION)


def assign_recommended_action(tier: str, risk_level: str) -> str:
    """Choose the recommended HR action.
    VERIFIED             → APPROVE
    REVIEW + MEDIUM      → REVIEW
    REVIEW + HIGH        → AUDITOR_REVIEW
    BLOCKED + HIGH       → MANUAL_VERIFICATION
    BLOCKED + CRITICAL   → ESCALATE
    """
    if tier == PaymentTier.VERIFIED:
        return RecommendedAction.APPROVE
    if tier == PaymentTier.REVIEW:
        return (
            RecommendedAction.AUDITOR_REVIEW
            if risk_level == RiskLevel.HIGH
            else RecommendedAction.REVIEW
        )
    return (
        RecommendedAction.ESCALATE
        if risk_level == RiskLevel.CRITICAL
        else RecommendedAction.MANUAL_VERIFICATION
    )


# =============================================================================
# ANOMALY DETECTION (RULE-BASED)
# =============================================================================


def build_anomalies(row: dict) -> list:
    """Produce typed, severity-labelled anomaly objects for one employee.

    Deterministic rules that run on top of model output.  Translate feature
    values into structured anomaly events the frontend can render directly.

    Args:
        row: Post-scoring feature dict for a single employee.

    Returns:
        List of anomaly dicts (may be empty for clean employees).
    """
    anomalies = []

    if row.get("Total Days Absent", 0) > 100:
        anomalies.append(
            {
                "type": AnomalyType.ATTENDANCE_ANOMALY,
                "severity": AnomalySeverity.HIGH,
                "description": f"{int(row['Total Days Absent'])} absent days — abnormally high.",
            }
        )
    if row.get("Avg Presence %", 100) < 20:
        anomalies.append(
            {
                "type": AnomalyType.ATTENDANCE_ANOMALY,
                "severity": AnomalySeverity.CRITICAL,
                "description": f"Average attendance of {row.get('Avg Presence %', 0):.1f}% is critically low.",
            }
        )
    if row.get("Months w/ Zero Attend.", 0) >= 3:
        anomalies.append(
            {
                "type": AnomalyType.GHOST_PATTERN,
                "severity": AnomalySeverity.HIGH,
                "description": (
                    f"{int(row['Months w/ Zero Attend.'])} months with zero attendance — "
                    "consistent with a ghost worker pattern."
                ),
            }
        )
    if row.get("Avg Unique Locations", 99) < 1.5:
        anomalies.append(
            {
                "type": AnomalyType.LOCATION_ANOMALY,
                "severity": AnomalySeverity.MEDIUM,
                "description": "Very few unique clock-in locations — possible clocking fraud.",
            }
        )
    if row.get("Acct Age (Mths)", 99) < 3:
        anomalies.append(
            {
                "type": AnomalyType.SYNTHETIC_IDENTITY,
                "severity": AnomalySeverity.MEDIUM,
                "description": "Bank account less than 3 months old — possible synthetic identity.",
            }
        )
    if row.get("BVN Acct Count", 1) > 2:
        anomalies.append(
            {
                "type": AnomalyType.DUPLICATE_BVN,
                "severity": AnomalySeverity.HIGH,
                "description": (
                    f"BVN linked to {int(row['BVN Acct Count'])} accounts — "
                    "potential identity duplication."
                ),
            }
        )
    if row.get("salary_band_violation", 0) == 1:
        anomalies.append(
            {
                "type": AnomalyType.SALARY_ANOMALY,
                "severity": AnomalySeverity.HIGH,
                "description": "Salary falls outside the acceptable range for this grade band.",
            }
        )
    if row.get("salary_roundness", 0) == 1:
        anomalies.append(
            {
                "type": AnomalyType.ROUND_SALARY_PATTERN,
                "severity": AnomalySeverity.LOW,
                "description": "Salary is a round multiple of 10,000 — common in fabricated records.",
            }
        )
    if row.get("same_day_joiners", 0) > 5:
        anomalies.append(
            {
                "type": AnomalyType.BULK_JOIN_PATTERN,
                "severity": AnomalySeverity.MEDIUM,
                "description": (
                    f"{int(row['same_day_joiners'])} employees share the same join date — "
                    "bulk-hire pattern associated with fictitious staff."
                ),
            }
        )
    return anomalies


def build_signals(row: dict) -> dict:
    """Return binary signal flags for quick frontend rendering."""
    return {
        "duplicate_bvn": row.get("BVN Acct Count", 1) > 2,
        "duplicate_nin": False,  # Requires cross-record NIN dedup; not yet implemented
        "salary_anomaly": bool(row.get("salary_band_violation", 0)),
        "ghost_pattern": row.get("Months w/ Zero Attend.", 0) >= 3,
        "synthetic_identity": row.get("Acct Age (Mths)", 99) < 3,
        "attendance_anomaly": (
            row.get("Avg Presence %", 100) < 20 or row.get("Total Days Absent", 0) > 100
        ),
        "device_anomaly": False,  # Requires device fingerprint data; not in scope
        "location_anomaly": row.get("Avg Unique Locations", 99) < 1.5,
        "liveness_failure": False,  # Requires biometric data; not in scope
    }


def get_top_signals(row: dict) -> list:
    """Return plain-English risk signal strings for the Gemini explanation prompt.
    Always returns at least one item.
    """
    signals = []
    if row.get("Total Days Absent", 0) > 100:
        signals.append("high number of absent days")
    if row.get("Avg Presence %", 100) < 20:
        signals.append("critically low attendance rate")
    if row.get("Months w/ Zero Attend.", 0) >= 3:
        signals.append("multiple months with zero attendance")
    if row.get("Acct Age (Mths)", 99) < 3:
        signals.append("very new bank account")
    if row.get("BVN Acct Count", 1) > 2:
        signals.append("BVN linked to multiple accounts")
    if row.get("salary_band_violation", 0) == 1:
        signals.append("salary outside grade band")
    if row.get("same_day_joiners", 0) > 5:
        signals.append("joined on same date as many others")
    if row.get("salary_roundness", 0) == 1:
        signals.append("suspiciously round salary amount")
    if not signals:
        signals.append("statistical anomaly across multiple payroll signals")
    return signals


# =============================================================================
# EMPLOYEE PROFILE EXTRACTION
# =============================================================================


def extract_employee_profile(
    row_raw: pd.Series,
    employee_id: str,
    row_mapped=None,
) -> dict:
    """Extract PII and HR profile fields from the original (pre-mapped) row.

    Checks the mapped row (canonical column names) first, then the raw row
    (original column names) as fallback.  This ensures fields are found
    regardless of whether the column mapper renamed them.

    Attempts multiple column name variants; defaults to None for absent
    columns.  Gender is normalised to the enum.

    Args:
        row_raw:     Single row from df_raw (original column names).
        employee_id: Resolved employee ID string.
        row_mapped:  Optional single row from df_mapped (canonical names).

    Returns:
        Dict conforming to the "employee" sub-object in the response schema.
    """
    raw = row_raw.to_dict() if hasattr(row_raw, "to_dict") else {}
    mapped = (
        row_mapped.to_dict()
        if row_mapped is not None and hasattr(row_mapped, "to_dict")
        else {}
    )

    def _norm_key(k: str) -> str:
        return str(k).lower().strip().replace("_", " ").replace("-", " ")

    raw_lk = {_norm_key(k): v for k, v in raw.items()}
    mapped_lk = {_norm_key(k): v for k, v in mapped.items()}

    def safe_get(keys: list, default=None):
        for k in keys:
            nk = _norm_key(k)
            v = mapped_lk.get(nk) or raw_lk.get(nk)
            if v is not None and str(v).strip() not in ("", "nan", "NaT", "<NA>"):
                return str(v).strip()
        return default

    def safe_float(keys: list):
        for k in keys:
            nk = _norm_key(k)
            v = mapped_lk.get(nk) or raw_lk.get(nk)
            try:
                f = float(v)
                return f
            except (KeyError, TypeError, ValueError):
                continue
        return None

    gender_raw = safe_get(["Gender", "gender", "Sex", "sex"], "")
    gender = {
        "m": Gender.MALE,
        "male": Gender.MALE,
        "f": Gender.FEMALE,
        "female": Gender.FEMALE,
    }.get(gender_raw.lower(), Gender.OTHER)

    full_name = safe_get(["Full Name", "Name", "Employee Name"])
    first_name = safe_get(["First Name", "first_name", "FirstName"])
    last_name = safe_get(["Last Name", "Surname", "last_name", "LastName"])
    middle_name = safe_get(["Middle Name", "middle_name", "MiddleName"])

    if full_name and not (first_name and last_name):
        parts = full_name.split()
        first_name = parts[0] if parts else None
        last_name = parts[-1] if len(parts) > 1 else None
        middle_name = middle_name or (" ".join(parts[1:-1]) if len(parts) > 2 else None)

    return {
        "employee_id": employee_id,
        "first_name": first_name,
        "last_name": last_name,
        "middle_name": middle_name,
        "email": safe_get(["Email", "email", "Email Address"]),
        "phone": safe_get(["Phone", "phone", "Mobile", "Phone Number"]),
        "date_of_birth": safe_get(["Date of Birth", "DOB", "dob"]),
        "gender": gender,
        "address": safe_get(["Address", "address", "Home Address"]),
        "department": safe_get(["Department", "department", "Dept"]),
        "position": safe_get(["Job Title", "Position", "Role", "Designation"]),
        "hire_date": safe_get(["Hire Date", "Start Date", "Date Joined", "hire_date"]),
        "termination_date": safe_get(["Termination Date", "Exit Date", "End Date"]),
        "employment_type": EmploymentType.FULL_TIME,
        "status": EmploymentStatus.ACTIVE,
        "base_salary": safe_float(["monthly_salary"]),
        "allowances": safe_float(["allowances", "Allowances"]),
        "deductions": safe_float(["deductions", "Deductions"]),
        "net_salary": safe_float(["net_salary", "Net Salary", "Net Pay"]),
        "bank_code": safe_get(["Bank Code", "bank_code"]),
        "bank_account_number": safe_get(
            ["Account Number", "Acct No", "bank_account_number"]
        ),
        "bank_account_name": safe_get(["Account Name", "bank_account_name"]),
        "nin": safe_get(["NIN", "nin", "National ID"]),
        "bvn": safe_get(["BVN", "bvn"]),
    }


# =============================================================================
# SYSTEM FLAGS
# =============================================================================


def build_system_flags(tier: str, risk_level: str) -> dict:
    """Determine downstream workflow triggers for an employee record.

    Logic:
        should_create_user           — VERIFIED only
        should_create_staff_profile  — VERIFIED or REVIEW
        requires_auditor_review      — BLOCKED, or REVIEW + HIGH/CRITICAL risk
        requires_manual_verification — BLOCKED + CRITICAL risk
    """
    return {
        "should_create_user": tier == PaymentTier.VERIFIED,
        "should_create_staff_profile": tier
        in (PaymentTier.VERIFIED, PaymentTier.REVIEW),
        "requires_auditor_review": (
            tier == PaymentTier.BLOCKED
            or (
                tier == PaymentTier.REVIEW
                and risk_level in (RiskLevel.HIGH, RiskLevel.CRITICAL)
            )
        ),
        "requires_manual_verification": (
            tier == PaymentTier.BLOCKED and risk_level == RiskLevel.CRITICAL
        ),
    }


# =============================================================================
# CONFIDENCE SCORE
# =============================================================================


def compute_confidence(trust_score: float, anomaly_count: int) -> float:
    """Estimate model confidence (0–1) in the assigned trust score.

    Higher when the score is extreme (near 0 or 100) and multiple corroborating
    anomalies were detected.  Lower for borderline scores near 50.

    Formula:
        base   = |trust_score − 50| / 50        (0 at midpoint, 1 at extremes)
        signal = min(anomaly_count, 5) / 5       (0–1, capped at 5 anomalies)
        result = 0.6 × base + 0.4 × signal
    """
    base = abs(trust_score - 50) / 50
    signal = min(anomaly_count, 5) / 5
    return round(0.6 * base + 0.4 * signal, 2)


# =============================================================================
# GEMINI AI EXPLANATION (ASYNC, PER-EMPLOYEE)
# Called only for REVIEW and BLOCKED employees to conserve API quota.
# =============================================================================


async def generate_explanation(
    employee_id: str,
    trust_score: float,
    tier: str,
    top_signals: list,
) -> str:
    """Generate a 2–3 sentence HR audit explanation via Gemini 2.5 Flash.

    Falls back to a deterministic template on API failure.

    Args:
        employee_id: Identifier shown to the auditor.
        trust_score: Trust score (0–100).
        tier:        REVIEW or BLOCKED.
        top_signals: Plain-English risk signal strings.

    Returns:
        Audit explanation string.
    """
    prompt = f"""You are a payroll audit assistant for an African HR platform.
Write a concise 2-3 sentence explanation for an HR manager about why this employee was flagged.
Be factual and professional. Do not use technical jargon.

Employee ID: {employee_id}
Trust Score: {trust_score}/100
Status: {tier}
Risk signals detected: {", ".join(top_signals)}

Write only the explanation. No headers, no bullet points."""

    try:
        async with httpx.AsyncClient(timeout=20) as client:
            resp = await client.post(
                "https://generativelanguage.googleapis.com/v1beta/models/"
                f"gemini-2.5-flash:generateContent?key={GEMINI_API_KEY}",
                headers={"Content-Type": "application/json"},
                json={
                    "contents": [{"parts": [{"text": prompt}]}],
                    "generationConfig": {
                        "maxOutputTokens": 500,
                        "temperature": 0.3,
                        "stopSequences": ["\n\n"],
                    },
                },
            )
        raw = resp.json()
        return raw["candidates"][0]["content"]["parts"][0]["text"].strip()
    except Exception as exc:
        print(f"[Gemini] Explanation failed for {employee_id}: {exc} — using template.")
        return (
            f"Employee {employee_id} received a trust score of {round(trust_score, 1)}/100. "
            f"Key risk signals detected: {', '.join(top_signals)}. "
            "HR review is recommended before processing this payment."
        )


# =============================================================================
# FILE PARSER
# =============================================================================


def parse_file(content: bytes, filename: str) -> pd.DataFrame:
    """Parse CSV or Excel bytes into a DataFrame.

    Raises:
        ValueError: Unsupported file extension.
    """
    fn = filename.lower()
    if fn.endswith(".csv"):
        return pd.read_csv(io.BytesIO(content))
    elif fn.endswith((".xlsx", ".xls")):
        return pd.read_excel(io.BytesIO(content))
    raise ValueError(
        "Unsupported file type. Please upload a .csv, .xlsx, or .xls file."
    )


# =============================================================================
# MAIN SCORING ENGINE
# =============================================================================


async def score_payroll(df_raw: pd.DataFrame, import_id: str = "") -> dict:
    """End-to-end payroll scoring pipeline.

    Steps:
        1.  Detect employee ID column.
        2.  ★ Map client columns → canonical schema (Tier1 fuzzy + Tier2 Gemini).
        3.  Detect scan type from mapped columns.
        4.  Normalise salary values.
        5.  Engineer Rinse features (RINSE_SCAN only).
        6.  Impute missing feature columns with 0.
        7.  Label-encode categorical columns.
        8.  Run model inference → ensemble probability → trust scores.
        9.  Assign tiers, risk levels, anomalies, and signals.
        10. Concurrently generate Gemini audit explanations for flagged employees.
        11. Assemble and return the full response object.

    Args:
        df_raw:    Raw DataFrame from parse_file().
        import_id: Client-supplied import identifier (passed through to response).

    Returns:
        Dict matching the canonical response schema v2.
        scan_metadata.column_mapping contains the audit trail of what was resolved.
    """
    start_ms = time.time()

    # ── Step 1: Resolve employee ID column (before column renaming) ───────────
    id_col = None
    for col in df_raw.columns:
        if col.lower().strip() in (
            "employee id",
            "employee_id",
            "emp_id",
            "staff id",
            "staff_id",
        ):
            id_col = col
            break
    employee_ids = (
        df_raw[id_col].values
        if id_col
        else [f"EMP-{i:04d}" for i in range(len(df_raw))]
    )

    # ── Step 2: Two-tier column mapping ───────────────────────────────────────
    # df_mapped has canonical column names; df_raw is kept intact for
    # extract_employee_profile() which reads original PII column names.
    df_mapped, col_mapping = await map_columns(df_raw.copy())

    # ── Step 3: Detect scan type ──────────────────────────────────────────────
    has_attendance = any(c in df_mapped.columns for c in ATTENDANCE_COLS)
    scan_type = ScanType.PAYROLL if has_attendance else ScanType.RINSE
    target_cols = FULL_FEATURE_COLUMNS if has_attendance else RINSE_FEATURE_COLUMNS

    # ── Step 4: Salary normalisation ─────────────────────────────────────────
    df_mapped = normalise_salary(df_mapped)

    # ── Step 5: Impute missing base feature columns with 0 ───────────────────
    # Must happen before engineer_rinse_features so base columns exist.
    for col in target_cols:
        if col not in df_mapped.columns:
            df_mapped[col] = 0

    # ── Step 6: Rinse feature engineering ────────────────────────────────────
    if not has_attendance:
        df_mapped = engineer_rinse_features(df_mapped)

    # ── Step 7: Label-encode categorical columns ──────────────────────────────
    for col in CATEGORICAL_COLS:
        if col in df_mapped.columns:
            df_mapped[col] = df_mapped[col].astype(str)
            try:
                df_mapped[col] = le.fit_transform(df_mapped[col])
            except Exception:
                df_mapped[col] = pd.Categorical(df_mapped[col]).codes

    # ── Step 8: Coerce any remaining object columns to numeric ──────────────
    # Prevents XGBoost "DataFrame.dtypes for data must be int, float, bool or
    # category" errors when label encoding produces object dtype.
    for col in target_cols:
        if col in df_mapped.columns and df_mapped[col].dtype == object:
            df_mapped[col] = pd.to_numeric(df_mapped[col], errors="coerce").fillna(0)

    # ── Step 9: Model inference ───────────────────────────────────────────────
    if has_attendance:
        features = df_mapped[FULL_FEATURE_COLUMNS].fillna(0)
        xgb_proba = xgb_full.predict_proba(features)[:, 1]
        iso_scores = iso_model.decision_function(features)
        iso_min, iso_max = iso_scores.min(), iso_scores.max()
        iso_proba = 1 - ((iso_scores - iso_min) / (iso_max - iso_min + 1e-9))
        ensemble = 0.70 * xgb_proba + 0.30 * iso_proba
    else:
        features = df_mapped[RINSE_FEATURE_COLUMNS].fillna(0)
        ensemble = xgb_rinse.predict_proba(features)[:, 1]

    trust_scores = ((1 - ensemble) * 100).round(1)

    # ── Step 9: Tiers, anomalies, signals ────────────────────────────────────
    tiers = [assign_tier(float(ts)) for ts in trust_scores]
    risk_levels = [assign_risk_level(float(ts)) for ts in trust_scores]
    anomaly_lists = []
    signal_dicts = []
    top_signal_lists = []
    for i in range(len(df_mapped)):
        row_dict = df_mapped.iloc[i].to_dict()
        anomaly_lists.append(build_anomalies(row_dict))
        signal_dicts.append(build_signals(row_dict))
        top_signal_lists.append(get_top_signals(row_dict))

    # ── Step 10: Concurrent Gemini audit explanations ─────────────────────────
    explanation_tasks: dict[int, asyncio.Task] = {}
    for i, (eid, ts, tier) in enumerate(zip(employee_ids, trust_scores, tiers)):
        if tier in (PaymentTier.REVIEW, PaymentTier.BLOCKED):
            explanation_tasks[i] = asyncio.create_task(
                generate_explanation(str(eid), float(ts), tier, top_signal_lists[i])
            )
    explanations: dict[int, str] = {}
    for i, task in explanation_tasks.items():
        explanations[i] = await task

    # ── Step 11: Assemble employee records ────────────────────────────────────
    employee_records = []
    for i, (eid, ts, tier, risk) in enumerate(
        zip(employee_ids, trust_scores, tiers, risk_levels)
    ):
        ts_f = float(ts)
        anomalies = anomaly_lists[i]
        ai_text = explanations.get(i, "")

        employee_records.append(
            {
                "employee": extract_employee_profile(df_raw.iloc[i], str(eid), df_mapped.iloc[i]),
                "analysis": {
                    "trust_score": ts_f,
                    "payment_tier": tier,
                    "risk_level": risk,
                    "status": assign_analysis_status(tier),
                    "action_required": tier != PaymentTier.VERIFIED,
                    "confidence_score": compute_confidence(ts_f, len(anomalies)),
                    "recommended_action": assign_recommended_action(tier, risk),
                    "anomalies": anomalies,
                    "signals": signal_dicts[i],
                    "ai_reasoning": [ai_text] if ai_text else [],
                },
                "system": build_system_flags(tier, risk),
            }
        )

    # ── Step 13: Summary ──────────────────────────────────────────────────────
    verified_count = sum(
        1
        for r in employee_records
        if r["analysis"]["payment_tier"] == PaymentTier.VERIFIED
    )
    review_count = sum(
        1
        for r in employee_records
        if r["analysis"]["payment_tier"] == PaymentTier.REVIEW
    )
    ghost_flag_count = sum(
        1
        for r in employee_records
        if r["analysis"]["payment_tier"] == PaymentTier.BLOCKED
    )
    total = len(employee_records)
    avg_trust = round(float(np.mean(trust_scores)), 1) if total else 0.0
    interception_pct = (
        round((review_count + ghost_flag_count) / total * 100, 1) if total else 0.0
    )

    return {
        "import_id": import_id,
        "scan_id": str(uuid.uuid4()),
        "scan_type": scan_type,
        "status": ScanStatus.COMPLETED,
        "processed_at": datetime.now(timezone.utc).isoformat(),
        "summary": {
            "total_records": total,
            "verified_count": verified_count,
            "review_count": review_count,
            "ghost_flag_count": ghost_flag_count,
            "interception_rate": interception_pct,
            "average_trust_score": avg_trust,
        },
        "employees": employee_records,
        "scan_metadata": {
            "model_version": MODEL_VERSION,
            "ruleset_version": RULESET_VERSION,
            "processing_time_ms": int((time.time() - start_ms) * 1000),
            # Audit trail: exactly which client columns were resolved and to what.
            # Useful for debugging unexpected imputation (score unusually low?
            # check this field to see if a key column was missed).
            "column_mapping": col_mapping,
        },
        "error": None,
    }


# =============================================================================
# FASTAPI APPLICATION
# =============================================================================

app = FastAPI(
    title="Ghost Worker Detection API",
    description=(
        "Payroll anomaly detection powered by an Isolation Forest + XGBoost ensemble "
        "with Gemini AI-generated audit explanations.\n\n"
        "**Column mapping**: uploaded files may use any column naming convention. "
        "Headers are automatically resolved to the canonical schema using local "
        "fuzzy matching (rapidfuzz, zero cost) with a Gemini-powered fallback for "
        "unrecognised names.  The resolved mapping is returned in "
        "`scan_metadata.column_mapping` for auditability."
    ),
    version="2.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Restrict to specific origins in production
    allow_methods=["*"],
    allow_headers=["*"],
)


# =============================================================================
# ENDPOINTS
# =============================================================================


@app.get("/health", summary="Liveness check")
async def health():
    """Returns 200 OK with service info. No auth required."""
    return {
        "status": "online",
        "message": "Ghost Worker Detection API is live",
        "models": "PAYROLL_SCAN (IsoForest + XGBoost) | RINSE_SCAN (XGBoost)",
        "version": "2.0.0",
        "column_mapping": "Tier1=rapidfuzz (local) | Tier2=Gemini fallback (1 call/file max)",
    }


@app.post("/score", summary="Score a payroll file")
async def score(
    file: UploadFile = File(..., description="Payroll file (.csv / .xlsx / .xls)"),
    import_id: str = Form(default="", description="Client-supplied import identifier"),
    company_name: str = Form(
        default="Unknown Company", description="Organisation name (metadata only)"
    ),
    location: str = Form(
        default="Unknown Location", description="Geographic location (metadata only)"
    ),
    branch_name: str = Form(
        default="Unknown Branch", description="Branch or business unit (metadata only)"
    ),
):
    """Score every employee in the uploaded payroll file.

    Column names in the uploaded file are automatically mapped to the canonical
    schema.  The mapping audit trail is returned in scan_metadata.column_mapping.

    Returns:
        JSON conforming to the Ghost Worker Detection response schema v2.

    Raises:
        400: File missing, unreadable, or unsupported format.
        500: Internal processing error.
    """
    if not file.filename:
        raise HTTPException(status_code=400, detail="No file provided.")

    try:
        content = await file.read()
        df_raw = parse_file(content, file.filename)
        results = await score_payroll(df_raw, import_id=import_id)

        results["company_name"] = company_name
        results["location"] = location
        results["branch_name"] = branch_name

        return results

    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))
