# =============================================================================
# app.py — Ghost Worker / Fraud Detection API
# Deployed on Hugging Face Spaces
#
# Endpoints:
#   GET  /health  — liveness check
#   POST /score   — upload a payroll CSV/Excel and receive a fraud analysis
#   GET  /docs    — Swagger UI (auto-generated by FastAPI)
#
# Detection pipeline:
#   1. Parse uploaded CSV/Excel payroll file
#   2. Detect scan type (Full Scan vs Rinse Scan) based on available columns
#   3. Normalise columns, salary values, and engineer additional features
#   4. Score each employee via an ensemble:
#        Full Scan  → 70% XGBoost (full) + 30% Isolation Forest
#        Rinse Scan → 100% XGBoost (rinse, lightweight)
#   5. Convert raw ensemble probability to a 0–100 trust score
#   6. Assign each employee a payment tier and risk classification
#   7. Generate AI-written audit explanations via Gemini (async, concurrent)
#   8. Return structured JSON conforming to the canonical response schema
#
# Response schema version: 2.0
# =============================================================================

import asyncio
import io
import json
import os
import pickle
import time
import uuid
from datetime import datetime, timezone

import httpx
import numpy as np
import pandas as pd
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware

# =============================================================================
# MODEL LOADING
# Models are stored alongside this script in the HF Space repository.
# All four artefacts must be present; the app will crash at startup if any
# are missing — this is intentional so deployments fail fast rather than
# silently serving wrong results.
# =============================================================================

with open("iso_forest_model.pkl", "rb") as f:
    iso_model = pickle.load(f)  # Isolation Forest — unsupervised anomaly detector

with open("xgb_model.pkl", "rb") as f:
    xgb_full = pickle.load(
        f
    )  # XGBoost trained on the full feature set (attendance + payroll)

with open("xgb_rinse_model.pkl", "rb") as f:
    xgb_rinse = pickle.load(
        f
    )  # XGBoost trained on payroll-only features (no attendance data)

with open("label_encoder.pkl", "rb") as f:
    le = pickle.load(f)  # LabelEncoder for categorical columns

print("All models loaded successfully.")

# =============================================================================
# ENVIRONMENT / SECRETS
# Set these as HF Space Secrets, never hard-code them here.
# =============================================================================

GEMINI_API_KEY = os.environ.get(
    "GEMINI_API_KEY", ""
)  # Google Gemini API key for AI explanations
DIVINE_WEBHOOK = os.environ.get(
    "WEBHOOK", ""
)  # Optional outbound webhook (reserved for future use)

# Current model/ruleset version strings embedded in every response for
# auditability and rollback tracking.
MODEL_VERSION = "2.0.0"
RULESET_VERSION = "2.0.0"

# =============================================================================
# FEATURE COLUMN DEFINITIONS
# These lists define the exact columns each model expects.  Order matters
# because XGBoost is sensitive to column order at inference time.
# =============================================================================

# Full feature set — used when the uploaded file contains attendance columns.
FULL_FEATURE_COLUMNS = [
    "Gender",
    "State",
    "Department",
    "Job Title",
    "Grade",
    "monthly_salary",
    "band_min",
    "band_max",
    "Bank Name",
    "Acct Age (Mths)",
    "attendance_pct",
    "Monthly Txns",
    "BVN Acct Count",
    "days_tenure",
    "days_since_active",
    "Months on Record",
    "Total Working Days",
    "Total Days Present",
    "Total Days Absent",
    "Total Days Leave",
    "Avg Presence %",
    "Months w/ Zero Attend.",
    "Max Consec. Zero Mths",
    "Avg CI Variance (mins)",
    "Avg Unique Locations",
]

# Base payroll features shared by both Rinse and Full scans.
RINSE_BASE_FEATURES = [
    "Gender",
    "State",
    "Department",
    "Job Title",
    "Grade",
    "monthly_salary",
    "band_min",
    "band_max",
    "Bank Name",
    "Acct Age (Mths)",
    "attendance_pct",
    "Monthly Txns",
    "BVN Acct Count",
    "days_tenure",
    "days_since_active",
]

# Rinse feature set — base payroll features plus four engineered signals.
RINSE_FEATURE_COLUMNS = RINSE_BASE_FEATURES + [
    "same_day_joiners",  # How many employees share the same join date
    "salary_roundness",  # 1 if salary is a suspiciously round multiple of 10,000
    "salary_band_violation",  # 1 if salary is >30% above band_max or <30% below band_min
    "salary_deviation",  # Normalised position of salary within the grade band
]

# Columns that will be label-encoded before model inference.
CATEGORICAL_COLS = ["Gender", "State", "Department", "Job Title", "Bank Name"]

# Attendance-specific columns; their presence triggers a Full Scan.
ATTENDANCE_COLS = [
    "Months on Record",
    "Total Working Days",
    "Total Days Present",
    "Total Days Absent",
    "Total Days Leave",
    "Avg Presence %",
    "Months w/ Zero Attend.",
    "Max Consec. Zero Mths",
    "Avg CI Variance (mins)",
    "Avg Unique Locations",
]

# =============================================================================
# SCHEMA CONSTANTS
# These enumerations mirror the canonical response schema (v2).
# Centralising them here makes it easy to extend the schema without hunting
# through business-logic functions.
# =============================================================================


class ScanType:
    RINSE = "RINSE_SCAN"
    PAYROLL = "PAYROLL_SCAN"  # was "Full Scan" in v1


class ScanStatus:
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class PaymentTier:
    VERIFIED = "VERIFIED"
    REVIEW = "REVIEW"
    BLOCKED = "BLOCKED"  # replaces "GHOST FLAG" in the output tier field


class RiskLevel:
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AnalysisStatus:
    CLEAR = "CLEAR"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    GHOST_FLAGGED = "GHOST_FLAGGED"
    BLOCKED = "BLOCKED"
    UNDER_INVESTIGATION = "UNDER_INVESTIGATION"


class RecommendedAction:
    APPROVE = "APPROVE"
    REVIEW = "REVIEW"
    BLOCK = "BLOCK"
    ESCALATE = "ESCALATE"
    MANUAL_VERIFICATION = "MANUAL_VERIFICATION"
    AUDITOR_REVIEW = "AUDITOR_REVIEW"


class AnomalyType:
    DUPLICATE_BVN = "DUPLICATE_BVN"
    DUPLICATE_NIN = "DUPLICATE_NIN"
    SALARY_ANOMALY = "SALARY_ANOMALY"
    GHOST_PATTERN = "GHOST_PATTERN"
    SYNTHETIC_IDENTITY = "SYNTHETIC_IDENTITY"
    ATTENDANCE_ANOMALY = "ATTENDANCE_ANOMALY"
    DEVICE_ANOMALY = "DEVICE_ANOMALY"
    LOCATION_ANOMALY = "LOCATION_ANOMALY"
    LIVENESS_FAILURE = "LIVENESS_FAILURE"
    MULTIPLE_BANK_USAGE = "MULTIPLE_BANK_USAGE"
    ROUND_SALARY_PATTERN = "ROUND_SALARY_PATTERN"
    BULK_JOIN_PATTERN = "BULK_JOIN_PATTERN"


class AnomalySeverity:
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class EmploymentType:
    FULL_TIME = "FULL_TIME"
    PART_TIME = "PART_TIME"
    CONTRACT = "CONTRACT"
    INTERN = "INTERN"
    TEMPORARY = "TEMPORARY"


class EmploymentStatus:
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"
    TERMINATED = "TERMINATED"
    ON_LEAVE = "ON_LEAVE"


class Gender:
    MALE = "MALE"
    FEMALE = "FEMALE"
    OTHER = "OTHER"


# =============================================================================
# COLUMN NORMALISATION
# =============================================================================


async def normalise_columns(df: pd.DataFrame, target_cols: list) -> pd.DataFrame:
    """Strip leading/trailing whitespace from all column headers.

    This is a lightweight normalisation step.  It does not rename or drop
    columns — unrecognised columns are simply ignored during feature
    selection (the model only sees the columns in target_cols).

    Args:
        df:          Raw DataFrame as parsed from the uploaded file.
        target_cols: Expected feature columns for the chosen scan type.
                     Not used inside this function but kept as a parameter
                     to preserve the public interface for future extensions
                     (e.g. fuzzy column matching via an LLM).

    Returns:
        DataFrame with stripped column headers.
    """
    df.columns = df.columns.str.strip()
    return df


# =============================================================================
# SALARY NORMALISATION
# =============================================================================


def normalise_salary(df: pd.DataFrame) -> pd.DataFrame:
    """Convert all salary values to a monthly amount.

    Some payroll exports record bi-weekly, weekly, or hourly figures.
    This function detects an optional pay-frequency column and converts
    accordingly so the model always receives a comparable monthly salary.

    Supported frequency strings (case-insensitive):
        monthly (default / no conversion)
        bi-weekly | twice monthly | bi-monthly | fortnightly  → ×2
        weekly                                                 → ×4.33
        hourly | per hour | hour                              → ×hours_per_week×4.33

    Also handles string salaries with comma thousands separators (e.g. "12,500").

    Args:
        df: DataFrame that must contain a "monthly_salary" column.

    Returns:
        DataFrame with monthly_salary normalised to a true monthly amount.
    """
    if "monthly_salary" not in df.columns:
        return df

    # Look for a pay-frequency column under several common names.
    freq_col = None
    for col in df.columns:
        if col.lower().strip() in (
            "pay frequency",
            "frequency",
            "payment type",
            "pay type",
            "pay cycle",
            "salary type",
        ):
            freq_col = col
            break

    if freq_col:

        def convert(row):
            freq = str(row[freq_col]).lower().strip()
            sal = row["monthly_salary"]
            if freq in ("bi-weekly", "twice monthly", "bi-monthly", "fortnightly"):
                return sal * 2
            elif freq in ("hourly", "per hour", "hour"):
                hours = row.get("hours_per_week", 40)
                return sal * hours * 4.33
            elif freq in ("weekly",):
                return sal * 4.33
            else:
                return sal  # Assume monthly

        df["monthly_salary"] = df.apply(convert, axis=1)

    # Handle string-formatted numbers (e.g. "85,000").
    if df["monthly_salary"].dtype == object:
        df["monthly_salary"] = df["monthly_salary"].str.replace(",", "", regex=False)
        df["monthly_salary"] = pd.to_numeric(
            df["monthly_salary"], errors="coerce"
        ).fillna(0)

    return df


# =============================================================================
# RINSE FEATURE ENGINEERING
# =============================================================================


def engineer_rinse_features(df: pd.DataFrame) -> pd.DataFrame:
    """Derive the four engineered features required by the Rinse model.

    These features capture payroll-level patterns that don't exist as raw
    columns in most HR exports:

        same_day_joiners      — frequency of the employee's join date across the
                                dataset; a spike suggests a batch of fictitious
                                hires added on the same day.
        salary_roundness      — binary flag; round multiples of 10,000 are common
                                in fabricated payroll records.
        salary_band_violation — binary flag; salary >130% of band_max or <70% of
                                band_min suggests miscategorisation or manipulation.
        salary_deviation      — normalised position within the grade band (0 = at
                                min, 1 = at max); values outside [0,1] indicate a
                                band violation.

    Args:
        df: DataFrame with at least days_tenure, monthly_salary, band_min, band_max.

    Returns:
        DataFrame with four new feature columns appended.
    """
    join_date_counts = df["days_tenure"].value_counts()
    df["same_day_joiners"] = df["days_tenure"].map(join_date_counts)

    df["salary_roundness"] = (df["monthly_salary"] % 10000 == 0).astype(int)

    df["salary_above_band"] = (df["monthly_salary"] > df["band_max"] * 1.3).astype(int)
    df["salary_below_band"] = (df["monthly_salary"] < df["band_min"] * 0.7).astype(int)
    df["salary_band_violation"] = (
        df["salary_above_band"] | df["salary_below_band"]
    ).astype(int)

    df["salary_deviation"] = (df["monthly_salary"] - df["band_min"]) / (
        df["band_max"] - df["band_min"] + 1
    )
    return df


# =============================================================================
# TIER / RISK ASSIGNMENT HELPERS
# =============================================================================


def assign_tier(score: float) -> str:
    """Map a trust score (0–100) to a payment tier.

    Thresholds:
        ≥75  → VERIFIED   (low risk; approve payment)
        ≥50  → REVIEW     (medium risk; human review required)
         <50  → BLOCKED    (high/critical risk; flag as potential ghost worker)

    Args:
        score: Trust score in the range [0, 100].

    Returns:
        One of the PaymentTier constants.
    """
    if score >= 75:
        return PaymentTier.VERIFIED
    elif score >= 50:
        return PaymentTier.REVIEW
    else:
        return PaymentTier.BLOCKED


def assign_risk_level(score: float) -> str:
    """Map a trust score to a qualitative risk level.

    Thresholds (inverse of trust — lower trust = higher risk):
        ≥75  → LOW
        ≥50  → MEDIUM
        ≥25  → HIGH
         <25  → CRITICAL

    Args:
        score: Trust score in the range [0, 100].

    Returns:
        One of the RiskLevel constants.
    """
    if score >= 75:
        return RiskLevel.LOW
    elif score >= 50:
        return RiskLevel.MEDIUM
    elif score >= 25:
        return RiskLevel.HIGH
    else:
        return RiskLevel.CRITICAL


def assign_analysis_status(tier: str) -> str:
    """Derive a detailed analysis status from the payment tier.

    Args:
        tier: One of the PaymentTier constants.

    Returns:
        One of the AnalysisStatus constants.
    """
    return {
        PaymentTier.VERIFIED: AnalysisStatus.CLEAR,
        PaymentTier.REVIEW: AnalysisStatus.REVIEW_REQUIRED,
        PaymentTier.BLOCKED: AnalysisStatus.GHOST_FLAGGED,
    }.get(tier, AnalysisStatus.UNDER_INVESTIGATION)


def assign_recommended_action(tier: str, risk_level: str) -> str:
    """Recommend the next action for an HR manager based on tier and risk.

    Logic:
        VERIFIED + LOW   → APPROVE
        REVIEW   + MEDIUM → REVIEW
        REVIEW   + HIGH   → AUDITOR_REVIEW
        BLOCKED  + HIGH   → MANUAL_VERIFICATION
        BLOCKED  + CRITICAL → BLOCK / ESCALATE

    Args:
        tier:       PaymentTier constant.
        risk_level: RiskLevel constant.

    Returns:
        One of the RecommendedAction constants.
    """
    if tier == PaymentTier.VERIFIED:
        return RecommendedAction.APPROVE
    if tier == PaymentTier.REVIEW:
        if risk_level == RiskLevel.HIGH:
            return RecommendedAction.AUDITOR_REVIEW
        return RecommendedAction.REVIEW
    # BLOCKED tier
    if risk_level == RiskLevel.CRITICAL:
        return RecommendedAction.ESCALATE
    return RecommendedAction.MANUAL_VERIFICATION


# =============================================================================
# ANOMALY DETECTION (RULE-BASED SIGNALS)
# =============================================================================


def build_anomalies(row: dict) -> list:
    """Inspect a scored employee row and return a list of anomaly objects.

    Each anomaly has a "type" (AnomalyType), "severity" (AnomalySeverity),
    and a human-readable "description".

    The rules below are deterministic and run on top of the model output;
    they translate raw feature values into labelled anomaly events that the
    frontend can render without further parsing.

    Args:
        row: Dictionary of feature values for a single employee (post-scoring).

    Returns:
        List of anomaly dicts, possibly empty if no rules fire.
    """
    anomalies = []

    # --- Attendance anomalies (Full Scan only) --------------------------------
    if row.get("Total Days Absent", 0) > 100:
        anomalies.append(
            {
                "type": AnomalyType.ATTENDANCE_ANOMALY,
                "severity": AnomalySeverity.HIGH,
                "description": f"Employee has {int(row['Total Days Absent'])} recorded absent days, "
                "which is abnormally high and may indicate a ghost worker.",
            }
        )

    if row.get("Avg Presence %", 100) < 20:
        anomalies.append(
            {
                "type": AnomalyType.ATTENDANCE_ANOMALY,
                "severity": AnomalySeverity.CRITICAL,
                "description": f"Average attendance rate of {row.get('Avg Presence %', 0):.1f}% is critically low.",
            }
        )

    if row.get("Months w/ Zero Attend.", 0) >= 3:
        anomalies.append(
            {
                "type": AnomalyType.GHOST_PATTERN,
                "severity": AnomalySeverity.HIGH,
                "description": f"{int(row['Months w/ Zero Attend.'])} months with zero attendance recorded — "
                "consistent with a ghost worker pattern.",
            }
        )

    if row.get("Avg Unique Locations", 99) < 1.5:
        anomalies.append(
            {
                "type": AnomalyType.LOCATION_ANOMALY,
                "severity": AnomalySeverity.MEDIUM,
                "description": "Clock-in records show very few unique locations, "
                "which may indicate clocking fraud.",
            }
        )

    # --- Banking / identity anomalies ----------------------------------------
    if row.get("Acct Age (Mths)", 99) < 3:
        anomalies.append(
            {
                "type": AnomalyType.SYNTHETIC_IDENTITY,
                "severity": AnomalySeverity.MEDIUM,
                "description": "Bank account is less than 3 months old — possible synthetic identity.",
            }
        )

    if row.get("BVN Acct Count", 1) > 2:
        anomalies.append(
            {
                "type": AnomalyType.DUPLICATE_BVN,
                "severity": AnomalySeverity.HIGH,
                "description": f"BVN linked to {int(row['BVN Acct Count'])} bank accounts — "
                "potential identity duplication.",
            }
        )

    # --- Salary anomalies ----------------------------------------------------
    if row.get("salary_band_violation", 0) == 1:
        anomalies.append(
            {
                "type": AnomalyType.SALARY_ANOMALY,
                "severity": AnomalySeverity.HIGH,
                "description": "Salary falls outside the acceptable range for this employee's grade band.",
            }
        )

    if row.get("salary_roundness", 0) == 1:
        anomalies.append(
            {
                "type": AnomalyType.ROUND_SALARY_PATTERN,
                "severity": AnomalySeverity.LOW,
                "description": "Salary is a round multiple of 10,000 — common in fabricated payroll entries.",
            }
        )

    # --- Bulk-join pattern ---------------------------------------------------
    if row.get("same_day_joiners", 0) > 5:
        anomalies.append(
            {
                "type": AnomalyType.BULK_JOIN_PATTERN,
                "severity": AnomalySeverity.MEDIUM,
                "description": f"{int(row['same_day_joiners'])} employees share the same join date — "
                "a bulk-hire pattern sometimes associated with fictitious staff.",
            }
        )

    return anomalies


def build_signals(row: dict) -> dict:
    """Build the binary signal flags object from a scored row.

    These Boolean flags give the frontend a quick summary of which anomaly
    categories fired for this employee, without needing to parse the full
    anomalies list.

    Args:
        row: Dictionary of feature values for a single employee.

    Returns:
        Dict of signal name → bool.
    """
    return {
        "duplicate_bvn": row.get("BVN Acct Count", 1) > 2,
        "duplicate_nin": False,  # NIN dedup requires cross-record lookup; not yet implemented
        "salary_anomaly": bool(row.get("salary_band_violation", 0)),
        "ghost_pattern": row.get("Months w/ Zero Attend.", 0) >= 3,
        "synthetic_identity": row.get("Acct Age (Mths)", 99) < 3,
        "attendance_anomaly": row.get("Avg Presence %", 100) < 20
        or row.get("Total Days Absent", 0) > 100,
        "device_anomaly": False,  # Requires device fingerprint data; not yet in scope
        "location_anomaly": row.get("Avg Unique Locations", 99) < 1.5,
        "liveness_failure": False,  # Requires biometric liveness data; not yet in scope
    }


def get_top_signals(row: dict) -> list:
    """Return a plain-English list of the most prominent risk signals.

    Used as input to the Gemini AI explanation prompt so the LLM can
    reference specific evidence rather than generating generic text.

    Args:
        row: Dictionary of feature values for a single employee.

    Returns:
        List of short descriptive strings (at least one item).
    """
    signals = []
    if row.get("Total Days Absent", 0) > 100:
        signals.append("high number of absent days")
    if row.get("Avg Presence %", 100) < 20:
        signals.append("critically low attendance rate")
    if row.get("Months w/ Zero Attend.", 0) >= 3:
        signals.append("multiple months with zero attendance")
    if row.get("Acct Age (Mths)", 99) < 3:
        signals.append("very new bank account")
    if row.get("BVN Acct Count", 1) > 2:
        signals.append("BVN linked to multiple accounts")
    if row.get("salary_band_violation", 0) == 1:
        signals.append("salary outside grade band")
    if row.get("same_day_joiners", 0) > 5:
        signals.append("joined on same date as many others")
    if row.get("salary_roundness", 0) == 1:
        signals.append("suspiciously round salary amount")
    if not signals:
        signals.append("statistical anomaly across multiple payroll signals")
    return signals


# =============================================================================
# EMPLOYEE PROFILE EXTRACTION
# =============================================================================


def extract_employee_profile(row_raw: pd.Series, employee_id: str) -> dict:
    """Extract PII and HR profile fields from a raw DataFrame row.

    Attempts to read well-known column names; defaults to None if the column
    is absent (the caller's file may not include all optional fields).

    The "gender" field is normalised to the MALE/FEMALE/OTHER enum.

    Args:
        row_raw:     A single row from the original (pre-feature-engineering) DataFrame.
        employee_id: The resolved employee identifier string.

    Returns:
        Dict conforming to the "employee" sub-object in the response schema.
    """
    raw = row_raw.to_dict() if hasattr(row_raw, "to_dict") else {}

    def safe_get(keys, default=None):
        """Try multiple column name variants and return the first match."""
        for k in keys:
            v = raw.get(k)
            if v is not None and str(v).strip() not in ("", "nan", "NaT"):
                return str(v).strip()
        return default

    # Normalise gender to enum
    gender_raw = safe_get(["Gender", "gender", "Sex", "sex"], "")
    gender_map = {
        "m": Gender.MALE,
        "male": Gender.MALE,
        "f": Gender.FEMALE,
        "female": Gender.FEMALE,
    }
    gender = gender_map.get(gender_raw.lower(), Gender.OTHER)

    # Attempt to resolve first / last name from various column conventions
    full_name = safe_get(["Full Name", "Name", "Employee Name"])
    first_name = safe_get(["First Name", "first_name", "FirstName"])
    last_name = safe_get(["Last Name", "Surname", "last_name", "LastName"])
    middle_name = safe_get(["Middle Name", "middle_name", "MiddleName"])

    if full_name and not (first_name and last_name):
        parts = full_name.split()
        first_name = parts[0] if parts else None
        last_name = parts[-1] if len(parts) > 1 else None
        middle_name = middle_name or (" ".join(parts[1:-1]) if len(parts) > 2 else None)

    return {
        "employee_id": employee_id,
        "first_name": first_name,
        "last_name": last_name,
        "middle_name": middle_name,
        "email": safe_get(["Email", "email", "Email Address"]),
        "phone": safe_get(["Phone", "phone", "Mobile", "Phone Number"]),
        "date_of_birth": safe_get(["Date of Birth", "DOB", "dob"]),
        "gender": gender,
        "address": safe_get(["Address", "address", "Home Address"]),
        "department": safe_get(["Department", "department", "Dept"]),
        "position": safe_get(["Job Title", "Position", "Role"]),
        "hire_date": safe_get(["Hire Date", "Start Date", "Date Joined", "hire_date"]),
        "termination_date": safe_get(["Termination Date", "Exit Date", "End Date"]),
        "employment_type": EmploymentType.FULL_TIME,  # Defaulted; extend if column exists
        "status": EmploymentStatus.ACTIVE,  # Defaulted; extend if column exists
        "base_salary": float(raw.get("monthly_salary", 0) or 0) or None,
        "allowances": float(raw["allowances"]) if "allowances" in raw else None,
        "deductions": float(raw["deductions"]) if "deductions" in raw else None,
        "net_salary": float(raw["net_salary"]) if "net_salary" in raw else None,
        "bank_code": safe_get(["Bank Code", "bank_code"]),
        "bank_account_number": safe_get(
            ["Account Number", "Acct No", "bank_account_number"]
        ),
        "bank_account_name": safe_get(["Account Name", "bank_account_name"]),
        "nin": safe_get(["NIN", "nin", "National ID"]),
        "bvn": safe_get(["BVN", "bvn"]),
    }


# =============================================================================
# SYSTEM FLAGS
# =============================================================================


def build_system_flags(tier: str, risk_level: str) -> dict:
    """Determine downstream system actions for each employee.

    These flags drive automated workflow triggers in the calling platform
    (e.g. whether to create a user account, send to an auditor queue, etc.).

    Logic:
        should_create_user            — only if VERIFIED
        should_create_staff_profile   — VERIFIED or REVIEW
        requires_auditor_review       — BLOCKED or HIGH/CRITICAL REVIEW
        requires_manual_verification  — BLOCKED with CRITICAL risk

    Args:
        tier:       PaymentTier constant.
        risk_level: RiskLevel constant.

    Returns:
        Dict of flag name → bool.
    """
    return {
        "should_create_user": tier == PaymentTier.VERIFIED,
        "should_create_staff_profile": tier
        in (PaymentTier.VERIFIED, PaymentTier.REVIEW),
        "requires_auditor_review": (
            tier == PaymentTier.BLOCKED
            or (
                tier == PaymentTier.REVIEW
                and risk_level in (RiskLevel.HIGH, RiskLevel.CRITICAL)
            )
        ),
        "requires_manual_verification": (
            tier == PaymentTier.BLOCKED and risk_level == RiskLevel.CRITICAL
        ),
    }


# =============================================================================
# CONFIDENCE SCORE
# =============================================================================


def compute_confidence(trust_score: float, anomaly_count: int) -> float:
    """Estimate model confidence (0–1) in the trust score.

    Confidence is high when the trust score is extreme (near 0 or 100) and
    the number of corroborating anomalies is non-zero for flagged records.
    It is lower for borderline scores around 50.

    Formula:
        base    = |trust_score - 50| / 50      (0 at midpoint, 1 at extremes)
        signal  = min(anomaly_count, 5) / 5     (0–1, capped at 5 anomalies)
        result  = 0.6 * base + 0.4 * signal

    Args:
        trust_score:   Float in [0, 100].
        anomaly_count: Number of rule-based anomalies that fired.

    Returns:
        Float in [0.0, 1.0] rounded to 2 decimal places.
    """
    base = abs(trust_score - 50) / 50
    signal = min(anomaly_count, 5) / 5
    return round(0.6 * base + 0.4 * signal, 2)


# =============================================================================
# GEMINI AI EXPLANATION (ASYNC)
# =============================================================================


async def generate_explanation(
    employee_id: str,
    trust_score: float,
    tier: str,
    top_signals: list,
) -> str:
    """Call the Gemini API to generate a plain-English audit explanation.

    The explanation is written for an HR manager — no technical jargon,
    factual, and concise (2–3 sentences).  It is stored in the
    "analysis.ai_reasoning" field of the response.

    Falls back to a template string if the API call fails so the rest of
    the response is never blocked by a Gemini outage.

    Args:
        employee_id: Identifier string shown to the auditor.
        trust_score: Rounded trust score (0–100).
        tier:        PaymentTier constant.
        top_signals: List of plain-English risk signal strings.

    Returns:
        AI-generated explanation string.
    """
    prompt = f"""You are a payroll audit assistant for an African HR platform.
Write a concise 2-3 sentence explanation for an HR manager about why this employee was flagged.
Be factual and professional. Do not use technical jargon.

Employee ID: {employee_id}
Trust Score: {trust_score}/100
Status: {tier}
Risk signals detected: {", ".join(top_signals)}

Write only the explanation. No headers, no bullet points."""

    try:
        async with httpx.AsyncClient(timeout=20) as client:
            response = await client.post(
                f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash"
                f":generateContent?key={GEMINI_API_KEY}",
                headers={"Content-Type": "application/json"},
                json={
                    "contents": [{"parts": [{"text": prompt}]}],
                    "generationConfig": {
                        "maxOutputTokens": 500,
                        "temperature": 0.3,
                        "stopSequences": ["\n\n"],
                    },
                },
            )
        raw = response.json()
        return raw["candidates"][0]["content"]["parts"][0]["text"].strip()
    except Exception as exc:
        print(f"[Gemini] Failed for {employee_id}: {exc} — using fallback template.")
        return (
            f"Employee {employee_id} received a trust score of {round(trust_score, 1)}/100. "
            f"Key risk signals detected: {', '.join(top_signals)}. "
            f"HR review is recommended before processing this payment."
        )


# =============================================================================
# FILE PARSER
# =============================================================================


def parse_file(content: bytes, filename: str) -> pd.DataFrame:
    """Parse a CSV or Excel file from raw bytes into a DataFrame.

    Args:
        content:  Raw file bytes from the HTTP upload.
        filename: Original filename (used to detect extension).

    Returns:
        Parsed DataFrame.

    Raises:
        ValueError: If the file extension is not .csv, .xlsx, or .xls.
    """
    filename = filename.lower()
    if filename.endswith(".csv"):
        return pd.read_csv(io.BytesIO(content))
    elif filename.endswith((".xlsx", ".xls")):
        return pd.read_excel(io.BytesIO(content))
    else:
        raise ValueError(
            "Unsupported file type. Please upload a CSV or Excel file (.csv, .xlsx, .xls)."
        )


# =============================================================================
# MAIN SCORING ENGINE
# =============================================================================


async def score_payroll(df_raw: pd.DataFrame, import_id: str = "") -> dict:
    """Core scoring pipeline.  Accepts a raw payroll DataFrame and returns
    a fully populated response object conforming to schema v2.

    Pipeline steps:
        1.  Detect employee ID column.
        2.  Detect scan type (Full vs Rinse) from available columns.
        3.  Normalise column names and salary values.
        4.  Engineer Rinse-only features if needed.
        5.  Impute any missing feature columns with 0.
        6.  Label-encode categorical columns.
        7.  Run model inference → ensemble probability → trust score.
        8.  Assign tier, risk level, and action flags.
        9.  Build rule-based anomalies and signal flags.
        10. Concurrently generate Gemini AI explanations for flagged employees.
        11. Assemble and return the full response object.

    Args:
        df_raw:    Raw DataFrame parsed from the uploaded file.
        import_id: Client-supplied import identifier (passed through to response).

    Returns:
        Dict matching the canonical response schema v2.
    """
    start_ms = time.time()

    # ── Step 1: Resolve employee ID column ───────────────────────────────────
    id_col = None
    for col in df_raw.columns:
        if col.lower().strip() in (
            "employee id",
            "employee_id",
            "emp_id",
            "staff id",
            "staff_id",
        ):
            id_col = col
            break
    employee_ids = (
        df_raw[id_col].values
        if id_col
        else [f"EMP-{i:04d}" for i in range(len(df_raw))]
    )

    # ── Step 2: Detect scan type ─────────────────────────────────────────────
    has_attendance = any(
        col.lower().strip() in [c.lower() for c in ATTENDANCE_COLS]
        for col in df_raw.columns
    )
    scan_type = ScanType.PAYROLL if has_attendance else ScanType.RINSE
    target_cols = FULL_FEATURE_COLUMNS if has_attendance else RINSE_FEATURE_COLUMNS

    # ── Step 3: Normalise columns and salary ─────────────────────────────────
    df = await normalise_columns(df_raw.copy(), target_cols)
    df = normalise_salary(df)

    # ── Step 4: Rinse feature engineering ────────────────────────────────────
    if not has_attendance:
        df = engineer_rinse_features(df)

    # ── Step 5: Impute missing columns ───────────────────────────────────────
    for col in target_cols:
        if col not in df.columns:
            df[col] = 0

    # ── Step 6: Encode categoricals ──────────────────────────────────────────
    for col in CATEGORICAL_COLS:
        if col in df.columns:
            df[col] = df[col].astype(str)
            try:
                df[col] = le.fit_transform(df[col])
            except Exception:
                # Fallback: pandas Categorical codes (−1 for unseen labels)
                df[col] = pd.Categorical(df[col]).codes

    # ── Step 7: Model inference ───────────────────────────────────────────────
    if has_attendance:
        df_features = df[FULL_FEATURE_COLUMNS].fillna(0)
        xgb_proba = xgb_full.predict_proba(df_features)[:, 1]
        iso_scores = iso_model.decision_function(df_features)
        # Normalise Isolation Forest scores to [0, 1] where 1 = most anomalous
        iso_min, iso_max = iso_scores.min(), iso_scores.max()
        iso_proba = 1 - ((iso_scores - iso_min) / (iso_max - iso_min + 1e-9))
        # Weighted ensemble: 70% supervised XGBoost + 30% unsupervised IsoForest
        ensemble = (0.70 * xgb_proba) + (0.30 * iso_proba)
    else:
        df_features = df[RINSE_FEATURE_COLUMNS].fillna(0)
        ensemble = xgb_rinse.predict_proba(df_features)[:, 1]

    # Convert fraud probability to a 0–100 trust score (higher = more trustworthy)
    trust_scores = ((1 - ensemble) * 100).round(1)

    # ── Step 8: Assign tiers and risk levels ──────────────────────────────────
    tiers = [assign_tier(float(ts)) for ts in trust_scores]
    risk_levels = [assign_risk_level(float(ts)) for ts in trust_scores]

    # ── Step 9: Build rule-based anomalies (sync) ─────────────────────────────
    anomaly_lists = []
    signal_dicts = []
    top_signal_lists = []
    for i in range(len(df)):
        row_dict = df.iloc[i].to_dict()
        anomaly_lists.append(build_anomalies(row_dict))
        signal_dicts.append(build_signals(row_dict))
        top_signal_lists.append(get_top_signals(row_dict))

    # ── Step 10: Concurrent Gemini AI explanations ────────────────────────────
    # Only generate explanations for non-VERIFIED employees to save API quota.
    explanation_tasks: dict[int, asyncio.Task] = {}
    for i, (eid, ts, tier) in enumerate(zip(employee_ids, trust_scores, tiers)):
        if tier in (PaymentTier.REVIEW, PaymentTier.BLOCKED):
            explanation_tasks[i] = asyncio.create_task(
                generate_explanation(str(eid), float(ts), tier, top_signal_lists[i])
            )

    # Await all tasks concurrently
    explanations: dict[int, str] = {}
    for i, task in explanation_tasks.items():
        explanations[i] = await task

    # ── Step 11: Assemble employee records ────────────────────────────────────
    employee_records = []
    for i, (eid, ts, tier, risk) in enumerate(
        zip(employee_ids, trust_scores, tiers, risk_levels)
    ):
        ts_float = float(ts)
        anomalies = anomaly_lists[i]
        signals = signal_dicts[i]
        top_sigs = top_signal_lists[i]
        ai_text = explanations.get(i, "")
        ai_reasoning = [ai_text] if ai_text else []

        confidence = compute_confidence(ts_float, len(anomalies))
        rec_action = assign_recommended_action(tier, risk)
        analysis_status = assign_analysis_status(tier)
        sys_flags = build_system_flags(tier, risk)
        emp_profile = extract_employee_profile(df_raw.iloc[i], str(eid))

        employee_records.append(
            {
                "employee": emp_profile,
                "analysis": {
                    "trust_score": ts_float,
                    "payment_tier": tier,
                    "risk_level": risk,
                    "status": analysis_status,
                    "action_required": tier != PaymentTier.VERIFIED,
                    "confidence_score": confidence,
                    "recommended_action": rec_action,
                    "anomalies": anomalies,
                    "signals": signals,
                    "ai_reasoning": ai_reasoning,
                },
                "system": sys_flags,
            }
        )

    # ── Step 12: Summary statistics ───────────────────────────────────────────
    verified_count = sum(
        1
        for r in employee_records
        if r["analysis"]["payment_tier"] == PaymentTier.VERIFIED
    )
    review_count = sum(
        1
        for r in employee_records
        if r["analysis"]["payment_tier"] == PaymentTier.REVIEW
    )
    ghost_flag_count = sum(
        1
        for r in employee_records
        if r["analysis"]["payment_tier"] == PaymentTier.BLOCKED
    )
    total = len(employee_records)
    avg_trust = round(float(np.mean(trust_scores)), 1) if total else 0.0
    interception_rate = (
        round((review_count + ghost_flag_count) / total * 100, 1) if total else 0.0
    )

    processing_time_ms = int((time.time() - start_ms) * 1000)

    return {
        "import_id": import_id,
        "scan_id": str(uuid.uuid4()),
        "scan_type": scan_type,
        "status": ScanStatus.COMPLETED,
        "processed_at": datetime.now(timezone.utc).isoformat(),
        "summary": {
            "total_records": total,
            "verified_count": verified_count,
            "review_count": review_count,
            "ghost_flag_count": ghost_flag_count,
            "interception_rate": interception_rate,
            "average_trust_score": avg_trust,
        },
        "employees": employee_records,
        "scan_metadata": {
            "model_version": MODEL_VERSION,
            "ruleset_version": RULESET_VERSION,
            "processing_time_ms": processing_time_ms,
        },
        "error": None,
    }


# =============================================================================
# FASTAPI APPLICATION
# =============================================================================

app = FastAPI(
    title="Ghost Worker Detection API",
    description=(
        "Payroll anomaly detection powered by an Isolation Forest + XGBoost ensemble "
        "with Gemini AI-generated audit explanations.  Upload a payroll CSV or Excel "
        "file to receive a structured fraud risk assessment for each employee."
    ),
    version="2.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Restrict to specific origins in production
    allow_methods=["*"],
    allow_headers=["*"],
)


# =============================================================================
# ENDPOINTS
# =============================================================================


@app.get(
    "/health",
    summary="Liveness check",
    description="Returns 200 OK with basic service information.  Use this to confirm the Space is running.",
)
async def health():
    """Liveness probe — no auth required."""
    return {
        "status": "online",
        "message": "Ghost Worker Detection API is live",
        "models": "Full Scan (IsoForest + XGBoost ensemble) | Rinse Scan (XGBoost)",
        "version": "2.0.0",
    }


@app.post(
    "/score",
    summary="Score a payroll file",
    description=(
        "Upload a CSV or Excel payroll export.  The API detects whether attendance "
        "data is present (Full / PAYROLL_SCAN) or absent (Rinse / RINSE_SCAN), scores "
        "every employee, and returns a structured JSON report with trust scores, "
        "anomalies, and AI-generated audit explanations."
    ),
)
async def score(
    file: UploadFile = File(..., description="Payroll file (.csv, .xlsx, or .xls)"),
    import_id: str = Form(
        default="",
        description="Client-supplied import identifier passed through to the response",
    ),
    company_name: str = Form(
        default="Unknown Company",
        description="Name of the organisation (metadata only)",
    ),
    location: str = Form(
        default="Unknown Location", description="Geographic location (metadata only)"
    ),
    branch_name: str = Form(
        default="Unknown Branch", description="Branch or business unit (metadata only)"
    ),
):
    """Score every employee in the uploaded payroll file.

    Returns:
        JSON conforming to the Ghost Worker Detection response schema v2.

    Raises:
        400: File missing, unreadable, or wrong format.
        500: Internal processing error (model failure, etc.).
    """
    if not file.filename:
        raise HTTPException(status_code=400, detail="No file provided.")

    try:
        content = await file.read()
        df_raw = parse_file(content, file.filename)
        results = await score_payroll(df_raw, import_id=import_id)

        # Attach request metadata to the top-level response
        results["company_name"] = company_name
        results["location"] = location
        results["branch_name"] = branch_name

        return results

    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))
